#!/bin/sh
git submodule update --init --recursive
rm -rf out
mkdir out
cd out
cmake -D CMAKE_INSTALL_PREFIX="./install" -DBGFX_BUILD_TOOLS=OFF -DBGFX_BUILD_EXAMPLES=OFF -DBGFX_INSTALL=OFF -DCMAKE_BUILD_TYPE=Release ..
make
make install
