#pragma once

#define VERSION_MAJOR @rtech_VERSION_MAJOR@
#define VERSION_MINOR @rtech_VERSION_MINOR@
#define VERSION_PATCH @rtech_VERSION_PATCH@
#define GIT_COMMIT_HASH "@GIT_COMMIT_HASH@"
#define GIT_BRANCH "@GIT_BRANCH@"
#define TODAY "@TODAY@"