#pragma once

#include <common.h>
#include <singleton.h>
#include <math/rectangle.h>
#include <math/vector2.h>
#include <math/vector3.h>
#include <math/vector4.h>
#include <math/quaternion.h>
#include <math/matrix.h>
#include <math/plane.h>
#include <math/ray.h>
#include <math/bounding_sphere.h>
#include <math/bounding_box.h>
#include <math/frustum.h>
#include <engine.h>
#include <input.h>
#include <app.h>
#include <scenenode.h>
#include <scene.h>
#include <textures/texture.h>
#include <package/package.h>
#include <package_manager.h>
#include <types/font.h>
#include <geometry/mesh.h>
#include <materials/material.h>
