name: master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  win64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./build.cmd
  macOSX:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./build.sh
